"""shipments + business_exposure.shipment_id

Revision ID: 08e41455a428
Revises: 618031ab0d7b
Create Date: 2026-08-28 20:47:40.735282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e41455a428'
down_revision: Union[str, Sequence[str], None] = '618031ab0d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('origin_port', sa.String(length=150), nullable=True),
    sa.Column('destination_country', sa.String(length=100), nullable=True),
    sa.Column('destination_port', sa.String(length=150), nullable=True),
    sa.Column('carrier', sa.String(length=150), nullable=True),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('etd', sa.DateTime(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('ata', sa.DateTime(), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_connection_id', sa.Integer(), nullable=True),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['supply_routes.id'], ),
    sa.ForeignKeyConstraint(['source_connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_organization_id'), 'shipments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shipments_product_id'), 'shipments', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipments_purchase_order_id'), 'shipments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_shipments_route_id'), 'shipments', ['route_id'], unique=False)
    op.create_index(op.f('ix_shipments_source_connection_id'), 'shipments', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_shipments_source_external_id'), 'shipments', ['source_external_id'], unique=False)
    op.create_index(op.f('ix_shipments_supplier_id'), 'shipments', ['supplier_id'], unique=False)
    op.add_column('business_exposures', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_business_exposures_shipment_id'), 'business_exposures', ['shipment_id'], unique=False)
    op.create_foreign_key(None, 'business_exposures', 'shipments', ['shipment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_exposures', type_='foreignkey')
    op.drop_index(op.f('ix_business_exposures_shipment_id'), table_name='business_exposures')
    op.drop_column('business_exposures', 'shipment_id')
    op.drop_index(op.f('ix_shipments_supplier_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_source_external_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_source_connection_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_route_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_purchase_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_product_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_organization_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
