"""integration layer: connections, raw_records, purchase_orders, provenance

Revision ID: 618031ab0d7b
Revises: e79e3c333a71
Create Date: 2026-08-28 19:17:56.008852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618031ab0d7b'
down_revision: Union[str, Sequence[str], None] = 'e79e3c333a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('cursor', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_organization_id'), 'connections', ['organization_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'entity_type', 'external_id', name='uq_raw_records_connection_entity_external')
    )
    op.create_index(op.f('ix_raw_records_connection_id'), 'raw_records', ['connection_id'], unique=False)
    op.create_index(op.f('ix_raw_records_entity_type'), 'raw_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_raw_records_id'), 'raw_records', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('incoterm', sa.String(length=10), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('expected_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_connection_id', sa.Integer(), nullable=True),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_source_connection_id'), 'purchase_orders', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_source_external_id'), 'purchase_orders', ['source_external_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('material_symbol', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source_connection_id', sa.Integer(), nullable=True),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_organization_id'), 'purchase_order_lines', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_product_id'), 'purchase_order_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_source_connection_id'), 'purchase_order_lines', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_source_external_id'), 'purchase_order_lines', ['source_external_id'], unique=False)
    op.add_column('expenses', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_expenses_source_connection_id'), 'expenses', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_expenses_source_external_id'), 'expenses', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('inventory', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_inventory_source_connection_id'), 'inventory', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_inventory_source_external_id'), 'inventory', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'inventory', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_source_connection_id'), 'orders', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_orders_source_external_id'), 'orders', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_materials', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('product_materials', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('product_materials', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_product_materials_source_connection_id'), 'product_materials', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_product_materials_source_external_id'), 'product_materials', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'product_materials', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_products_source_connection_id'), 'products', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_products_source_external_id'), 'products', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'products', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('suppliers', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('suppliers', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_suppliers_source_connection_id'), 'suppliers', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_suppliers_source_external_id'), 'suppliers', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('supply_routes', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('supply_routes', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('supply_routes', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_supply_routes_source_connection_id'), 'supply_routes', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_supply_routes_source_external_id'), 'supply_routes', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'supply_routes', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('source_external_id', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_transactions_source_connection_id'), 'transactions', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_transactions_source_external_id'), 'transactions', ['source_external_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_source_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_connection_id'), table_name='transactions')
    op.drop_column('transactions', 'synced_at')
    op.drop_column('transactions', 'source_external_id')
    op.drop_column('transactions', 'source_connection_id')
    op.drop_constraint(None, 'supply_routes', type_='foreignkey')
    op.drop_index(op.f('ix_supply_routes_source_external_id'), table_name='supply_routes')
    op.drop_index(op.f('ix_supply_routes_source_connection_id'), table_name='supply_routes')
    op.drop_column('supply_routes', 'synced_at')
    op.drop_column('supply_routes', 'source_external_id')
    op.drop_column('supply_routes', 'source_connection_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_source_external_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_source_connection_id'), table_name='suppliers')
    op.drop_column('suppliers', 'synced_at')
    op.drop_column('suppliers', 'source_external_id')
    op.drop_column('suppliers', 'source_connection_id')
    op.drop_column('suppliers', 'lead_time_days')
    op.drop_column('suppliers', 'city')
    op.drop_column('suppliers', 'country')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_source_external_id'), table_name='products')
    op.drop_index(op.f('ix_products_source_connection_id'), table_name='products')
    op.drop_column('products', 'synced_at')
    op.drop_column('products', 'source_external_id')
    op.drop_column('products', 'source_connection_id')
    op.drop_constraint(None, 'product_materials', type_='foreignkey')
    op.drop_index(op.f('ix_product_materials_source_external_id'), table_name='product_materials')
    op.drop_index(op.f('ix_product_materials_source_connection_id'), table_name='product_materials')
    op.drop_column('product_materials', 'synced_at')
    op.drop_column('product_materials', 'source_external_id')
    op.drop_column('product_materials', 'source_connection_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_source_external_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_connection_id'), table_name='orders')
    op.drop_column('orders', 'synced_at')
    op.drop_column('orders', 'source_external_id')
    op.drop_column('orders', 'source_connection_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_source_external_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_source_connection_id'), table_name='inventory')
    op.drop_column('inventory', 'synced_at')
    op.drop_column('inventory', 'source_external_id')
    op.drop_column('inventory', 'source_connection_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_source_external_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_source_connection_id'), table_name='expenses')
    op.drop_column('expenses', 'synced_at')
    op.drop_column('expenses', 'source_external_id')
    op.drop_column('expenses', 'source_connection_id')
    op.drop_index(op.f('ix_purchase_order_lines_source_external_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_source_connection_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_product_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_organization_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_source_external_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_source_connection_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_raw_records_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_entity_type'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_connection_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_connections_organization_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
