"use client";

import { useEffect, useState } from "react";

import { RefreshCw, Stamp } from "lucide-react";

import { apiRequest } from "@/lib/api";

import PageHeader from "@/app/components/PageHeader";
import Panel from "@/app/components/Panel";
import SeverityBadge from "@/app/components/SeverityBadge";
import { EmptyCard } from "@/app/components/StateCard";

interface Approval {
  id: number;
  organization_id: number;
  user_id: number;
  recommendation: string;
  scenario: string;
  event_id: number | null;
  comment: string | null;
  status: string;
  approved_at: string | null;
}

interface CreateApprovalResponse {
  status: string;
  approval: Approval;
}

const inputClass =
  "w-full rounded-lg border border-hairline bg-panel-raised px-3.5 py-2.5 text-sm outline-none transition focus:border-accent focus:ring-2 focus:ring-accent/20";

export default function ApprovalsPage() {
  const [approvals, setApprovals] = useState<Approval[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState("");

  const [recommendation, setRecommendation] = useState(
    "Activate alternative supply routes for the Red Sea disruption.",
  );
  const [scenario, setScenario] = useState("Red Sea shipping disruption");
  const [eventId, setEventId] = useState("");
  const [comment, setComment] = useState(
    "Approved for executive review and operational planning.",
  );

  async function loadApprovals() {
    try {
      setLoading(true);
      setError("");
      setApprovals(
        await apiRequest<Approval[]>("/approvals", { method: "GET" }),
      );
    } catch (err) {
      console.error("Failed to load approvals:", err);
      setError(
        err instanceof Error ? err.message : "Failed to load approvals.",
      );
    } finally {
      setLoading(false);
    }
  }

  async function handleCreateApproval() {
    try {
      setCreating(true);
      setError("");

      const response = await apiRequest<CreateApprovalResponse>(
        "/approvals",
        {
          method: "POST",
          body: JSON.stringify({
            recommendation,
            scenario,
            event_id: eventId ? Number(eventId) : null,
            comment: comment || null,
          }),
        },
      );

      setApprovals((current) => [response.approval, ...current]);
    } catch (err) {
      console.error("Failed to create approval:", err);
      setError(
        err instanceof Error ? err.message : "Failed to create approval.",
      );
    } finally {
      setCreating(false);
    }
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- initial fetch
    loadApprovals();
  }, []);

  return (
    <div className="p-6 lg:p-8">
      <PageHeader
        icon={Stamp}
        eyebrow="Governance & Decision Control"
        title="Approvals"
        description="Review and record business recommendations generated by HEX before operational decisions are implemented."
      />

      {error && (
        <div className="mb-6 rounded-lg border border-critical/30 bg-critical/5 p-3 text-sm text-critical">
          {error}
        </div>
      )}

      <div className="grid gap-5 lg:grid-cols-[400px_1fr]">
        <Panel label="Record Decision" title="New Approval" tone="live">
          <div className="space-y-4">
            <div>
              <label className="eyebrow mb-1.5 block">Recommendation</label>
              <textarea
                value={recommendation}
                onChange={(e) => setRecommendation(e.target.value)}
                rows={5}
                className={inputClass}
              />
            </div>

            <div>
              <label className="eyebrow mb-1.5 block">Scenario</label>
              <input
                value={scenario}
                onChange={(e) => setScenario(e.target.value)}
                className={inputClass}
              />
            </div>

            <div>
              <label className="eyebrow mb-1.5 block">Event ID</label>
              <input
                type="number"
                value={eventId}
                onChange={(e) => setEventId(e.target.value)}
                placeholder="Optional"
                className={inputClass}
              />
            </div>

            <div>
              <label className="eyebrow mb-1.5 block">Comment</label>
              <textarea
                value={comment}
                onChange={(e) => setComment(e.target.value)}
                rows={4}
                className={inputClass}
              />
            </div>

            <button
              type="button"
              onClick={handleCreateApproval}
              disabled={creating}
              className="w-full rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-bg transition hover:bg-accent/90 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {creating ? "Recording decision…" : "Record Approval"}
            </button>
          </div>
        </Panel>

        <Panel
          label="Audit Trail"
          title="Approval History"
          action={
            <button
              type="button"
              onClick={loadApprovals}
              disabled={loading}
              className="inline-flex items-center gap-2 rounded-lg border border-hairline px-3 py-1.5 text-sm font-medium text-dim transition hover:text-white disabled:opacity-60"
            >
              <RefreshCw
                size={14}
                className={loading ? "animate-spin" : ""}
              />
              Refresh
            </button>
          }
        >
          {loading ? (
            <p className="rounded-lg bg-panel-raised p-6 text-center text-sm text-dim">
              Loading approval history…
            </p>
          ) : approvals.length === 0 ? (
            <EmptyCard message="No approvals recorded. Create the first decision record using the form." />
          ) : (
            <div className="space-y-4">
              {approvals.map((approval) => (
                <article
                  key={approval.id}
                  className="rounded-lg border border-hairline p-4"
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="num eyebrow">
                        Approval #{approval.id}
                      </p>
                      <h3 className="mt-1 font-semibold text-white">
                        {approval.scenario}
                      </h3>
                    </div>
                    <SeverityBadge value={approval.status} />
                  </div>

                  <div className="mt-4 rounded-lg bg-panel-raised p-3">
                    <p className="eyebrow">Recommendation</p>
                    <p className="mt-1.5 whitespace-pre-wrap text-sm leading-6 text-dim">
                      {approval.recommendation}
                    </p>
                  </div>

                  {approval.comment && (
                    <div className="mt-3">
                      <p className="eyebrow">Comment</p>
                      <p className="mt-1 text-sm text-dim">
                        {approval.comment}
                      </p>
                    </div>
                  )}

                  <div className="num mt-4 grid gap-2 text-xs text-mute sm:grid-cols-3">
                    <span>User #{approval.user_id}</span>
                    <span>Event {approval.event_id ?? "—"}</span>
                    <span>
                      {approval.approved_at
                        ? new Date(
                            approval.approved_at,
                          ).toLocaleString()
                        : "—"}
                    </span>
                  </div>
                </article>
              ))}
            </div>
          )}
        </Panel>
      </div>

      <div className="mt-5">
        <Panel label="Governance Note" title="How approvals are recorded" tone="elevated">
          <p className="max-w-4xl text-sm leading-6 text-dim">
            HEX records recommendations and business decisions so high-impact
            actions remain traceable. The current backend implementation
            automatically marks newly created approval records as APPROVED.
          </p>
        </Panel>
      </div>
    </div>
  );
}
